//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YaYoBe_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public string Cono { get; set; }
        public int StudentId { get; set; }
        public int SemesterId { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
    }
}
